# Generated by Django 4.2.3 on 2023-07-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_filter_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sku',
        ),
        migrations.AddField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('NEW', 'NEW'), ('OLD', 'OLD')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='products',
            name='filter_price',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='members.filter_price'),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], default='', max_length=160),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='products',
            name='unique_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
