# Generated by Django 4.2.3 on 2023-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_colors_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='productSize',
            field=models.CharField(default='', max_length=50, verbose_name='productSize '),
        ),
        migrations.AlterField(
            model_name='size',
            name='productSize_count',
            field=models.CharField(max_length=50, verbose_name='productSize count'),
        ),
    ]
