# Generated by Django 4.2.3 on 2023-07-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_categories_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='productAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/img')),
                ('price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.products')),
            ],
            options={
                'verbose_name_plural': '7. productAttribute',
            },
        ),
    ]
